package com.health_insurance.enrollment_model;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.kie.api.definition.type.Label;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("Member Record")
public class MemberRecord implements Serializable {

	static final long serialVersionUID = 1L;

	@Label(value = "Member Id")
	private Integer id;
	@Label(value = "Date of Birth")
	private Date dateOfBirth;
	@Label(value = "Maintenance Type Code")
	private String maintenanceTypeCode;
	@Label(value = "Task Complexity")
	private Integer taskComplexity;
	@Label(value = "Valid Record")
	private Boolean isValid;

	public MemberRecord() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getMaintenanceTypeCode() {
		return this.maintenanceTypeCode;
	}

	public void setMaintenanceTypeCode(String maintenanceTypeCode) {
		this.maintenanceTypeCode = maintenanceTypeCode;
	}

	public Integer getTaskComplexity() {
		return this.taskComplexity;
	}

	public void setTaskComplexity(Integer taskComplexity) {
		this.taskComplexity = taskComplexity;
	}

	public Boolean getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

	@Override
	public String toString() {
		final ObjectMapper objectMapper = new ObjectMapper();
		try {
			objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
			return objectMapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}
		return "";
	}

	public MemberRecord(Integer id, Date dateOfBirth,
			String maintenanceTypeCode,
			Integer taskComplexity,
			Boolean isValid) {
		this.id = id;
		this.dateOfBirth = dateOfBirth;
		this.maintenanceTypeCode = maintenanceTypeCode;
		this.taskComplexity = taskComplexity;
		this.isValid = isValid;
	}

}